test:test.cc ./binary_tree/binary_tree.cc
	g++ -std=c++11 test.cc ./binary_tree/binary_tree.cc -o test

test_gdb:test.cc ./binary_tree/binary_tree.cc
	g++ -std=c++11 -g test.cc ./binary_tree/binary_tree.cc -o test_gdb
